### ISSUE TITLE
Consider Redeploying Backend to an Alternative Service

### ISSUE THREAD

**Issue by Enigma-I-am** [MartinsOnuoha/VueQR#1]
# Description
As of November 28, 2022, Heroku's free plan, which this project has been utilizing for backend deployment, has been deprecated. This has prompted the need to explore alternative hosting options to ensure the continued availability and stability of our project's backend infrastructure.

# Proposed Solution
After researching and evaluating potential alternatives, I have identified two promising options that align well with our project's requirements and budget considerations: [Render](https://render.com/) and [Fly.io](http://fly.io/). Both of these platforms offer robust features, reliable performance, and competitive pricing, making them suitable candidates for hosting our backend.

**Comment by MartinsOnuoha** [comment]
Thanks for the pointer @Enigma-I-am , we're now back on Rendr 🎉
